name: cfa
channels:
  - conda-forge
dependencies:
  - python=3.11  # Databricks compatible version
  - black
  - faker
  - flake8
  - isort
  - pip
  - ipython
  - jupyterlab
  - matplotlib
  - notebook
  - numpy
  - pandas
  - scikit-learn
  - prophet
  - statsmodels
  - pyod
  - pyspark=3.5
  - delta-spark
  - pip:
    - python-dotenv
    - mkdocs
    - mlflow
    - databricks-sdk
    - -e .
